### ISSUE TITLE
Docker-compose?

### ISSUE THREAD

**Issue by viriatusX** [yfhme/y-cs-firewall-bouncer#90]
### What would you like to be added?

How do I install it in Docker-Compose? 
I've tried but I'm not successful.
Thanks! 

### Why is this needed?

To be able to install cs-firewall on any NAS /UNRAID.

**Comment by yfhyou** [comment]
Sorry didn't think anyone else would use this 😄 

I just updated the readme to include some installation information.

**Comment by viriatusX** [comment]
Thanks :)
